<?
namespace PHPMailer\customPHPMailer;

ini_set('error_reporting', E_ERROR);
//ini_set('error_reporting', E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

require 'Exception.php';
require 'PHPMailer.php';
require 'SMTP.php';


class PHPMailer extends \PHPMailer\PHPMailer\PHPMailer{
    public function __construct($exceptions = null)
    {
        parent::__construct($exceptions);

        // Тут в принципе можно ничего не трогать
        $this->CharSet = 'UTF-8';

    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function isSMTP()
    {
        $this->SMTPAuth = true;
        $this->SMTPSecure = 'ssl';
        $this->Port = 465;

        parent::isSMTP(); // TODO: Change the autogenerated stub
    }
}

class Exception extends \PHPMailer\PHPMailer\Exception{

}

class SMTP extends \PHPMailer\PHPMailer\SMTP{

}